basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: User Service.
  title: User Service API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
